#!/usr/bin/env bash
source env/bin/activate
python -m pip list --outdated --format=json | jq -r '.[] | "\(.name)==\(.latest_version)"' | xargs -n1 pip install -U
pip freeze > requirements.txt
deactivate
